apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notejam-db
spec:
  serviceName: "notejam-db"
  replicas: 1
  selector:
    matchLabels:
      app: notejam-db
  template:
    metadata:
      labels:
        app: notejam-db
    spec:
    # volume configuration for the pod
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
      - name: notejam-db
        image: anshu0895/notejam-db:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "anshu"
          - name: POSTGRES_PASSWORD
            value: "anshu"
          - name: POSTGRES_DB
            value: "notejam"
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
