services:
  app:
    build: .
    container_name: notejam_app
    restart: always
    ports:
      - "5000:4000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: anshu
      DB_PASSWORD: anshu
      DB_NAME: notejam
      DB_PORT: 5432   # <-- Add this line
    networks:
      - notejam_network

  db:
    image: postgres:latest
    container_name: notejam_db
    restart: always
    environment:
      POSTGRES_USER: anshu
      POSTGRES_PASSWORD: anshu
      POSTGRES_DB: notejam
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - notejam_network

networks:
  notejam_network:
    name: notejam_network
    external: true


volumes:
  pgdata: